### ISSUE TITLE
Vulnerable Spring-JVM dependency via io.kotest: kotest-extensions-spring-jvm

### ISSUE THREAD

**Issue by tnleeuw** [pavleprica/kotlin-cache#3]
In the `pom.xml` file there's a dependency on `io.kotest: kotest-extensions-spring-jvm` which is not marked with `<scope>test</test>` and thus it looks like a lot of Spring libs will be pulled into the application using the version that kotest depends on.

My application doesn't use any Spring and the cache itself shouldn't depend on Spring, in my understanding?
So this dependency should have scope `test`.

IntelliJ flagged the dependency I added on `kotlin-cache` as having a transitive dependency on version of Spring Framework that has vulnerabilities, which of course would not be a good thing! :-)

Easy enough to work around in my project for now but a fix would be appreciated. :-)

**Comment by pavleprica** [comment]
Hey @tnleeuw !

Thank you very much for pointing it out! I'll focus on it as soon as possible!

**Comment by tnleeuw** [comment]
Great, thanks!

I can perhaps also supply a patch.

However now trying to actually include the cache code it seems I have a bigger issue: dependency on Java13 while my project still uses Java11. :-(

I need to see if I can upgrade JDK on our services without risks.

**Comment by pavleprica** [comment]
Feel free to! 

> I need to see if I can upgrade JDK on our services without risks.

Please don't! I used 13 as a default because at that time I was relying on that. I will revert it to 8 since it's Kotlin and shouldn't have an impact. Also, Java 13 isn't an LTS version, so that is a bit brave from me and at that time my company's side. :) 

I will do my best to look at this today, I hope that's ok with you. :)

**Comment by tnleeuw** [comment]
That will be fine!
I started investigating if I could find docker images for Java 17 JRE as that's latest LTS but if the Cache project will be built with Java8 or Java 11 instead that will be fine with me as well. ;-)
I'll see about creating some patches today!

**Comment by tnleeuw** [comment]
@pavleprica Looking at the overall dependencies of the project, is it OK to bump the Kotlin version to 1.6? Or should I keep it at 1.4.x?

I'm checking if I can upgrade the `kotest` dependency to the latest version somehow (5.2.1) but that is compiled against Kotlin 1.6!

Also, it appears that at least some of the tests really want to have Java11 or higher

**Comment by pavleprica** [comment]
I would say yes, but with a pre-check. We should check how is the compatibility between 1.6 and 1.5. I think Kotlin has moments of breaking those. :) 

> Also, it appears that at least some of the tests really want to have Java11 or higher

Hmm, I'll jump in to see where it has a dependency. But 11 is perfectly fine.

**Comment by tnleeuw** [comment]
Some tests check `Optional.isEmpty` which is  added in Java11.

**Comment by pavleprica** [comment]
Yes I see, but for some reason it fails even on Java 11. I'll investigate more definitely. Thanks for pointing out!

**Comment by pavleprica** [comment]
@tnleeuw I think it's something worse actually. :) 
It's a flaky test. I lowered it to Java 8, yet it passes without issues, but it also fails. Depends on the run. I'll see to fix that one!

**Comment by tnleeuw** [comment]
It builds for me with Java11!

**Comment by tnleeuw** [comment]
@pavleprica Thanks for the quick review and merge! :)

**Comment by pavleprica** [comment]
@tnleeuw Thank you for pointing out the issue and patching it! :D

**Comment by tnleeuw** [comment]
My pleasure!

**Comment by tnleeuw** [comment]
Just one question btw @pavleprica : How long do you expect it to take for the new release to show up on the Maven repository?
(I have little experience with how long one has to wait for that in general! 😁)

**Comment by pavleprica** [comment]
@tnleeuw Usually it's a few hours. But for now, it seems it's taking a bit more. I follow it [here](https://mvnrepository.com/artifact/io.github.pavleprica/kotlin-cache). I'll definitely post a comment here when it's up. :)

**Comment by tnleeuw** [comment]
Yeah I've been refreshing this link as well as mvnrepository.com:

https://search.maven.org/artifact/io.github.pavleprica/kotlin-cache

😁

**Comment by pavleprica** [comment]
@tnleeuw Also, if you wish for me to put your data as a developer, please do email me in this format
```xml
<developer>
    <name>Pavle Prica</name>
    <url>https://github.com/pavleprica</url>
    <email>pavle.prica5@gmail.com</email>
</developer>
```
I will make a release with it as well. :)

**Comment by pavleprica** [comment]
@tnleeuw took it awhile, but it's out. :)

**Comment by tnleeuw** [comment]
Yes, I see it indeed! Thanks!

Adding me as developer, perhaps if/when I submit some more patches and I make a somewhat more substantial contribution to the code. ;-)

Thanks for thinking about it in any case! :-)
